---
title: "Untitled"
author: "Connor Cabrey"
date: "2022-12-04"
output: pdf_document
---
---
title: "ML_Project"
author: "Yuka Chen"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(tidymodels)
library(fastDummies)
library(janitor)

H1B <- read_csv(file = "C:\\Users\\jermj\\OneDrive\\Desktop\\H1B_Project_ML\\Data\\H1B_Initial_Tidy.csv")

#adding waiting time variable and deselecting unnecessary variables
H1B <- H1B %>% 
  mutate(WAITING_PERIOD = DECISION_DATE- RECEIVED_DATE) |> 
  dplyr::select(-c(DECISION_DATE, REFILE, FW_OWNERSHIP_INTEREST, REQUIRED_TRAINING, RECEIVED_DATE, FOREIGN_WORKER_LIVE_ON_PREM, PW_SOC_TITLE, JOB_TITLE, EMPLOYER_NAME, EMPLOYER_CITY, EMPLOYER_STATE_PROVINCE, FOREIGN_WORKER_LIVE_IN_DOM_SER, wAGE_OFFER_AVG, WORKSITE_CITY, WORKSITE_STATE, JOB_TITLE, ACCEPT_FOREIGN_EDUCATION, FOREIGN_WORKER_BIRTH_COUNTRY, FOREIGN_WORKER_EMPL_PAY_FOR_ED,  FOREIGN_WORKER_INFO_MAJOR, APP_FOR_COLLEGE_U_TEACHER, FOREIGN_WORKER_YRS_ED_COMP, FOREIGN_WORKER_ED_INST_COUNTRY, FOREIGN_WORKER_ALT_ED_EXP, FOREIGN_WORKER_ALT_OCC_EXP, OFFERED_TO_APPL_FOREIGN_WORKER))

#Creating Hourly Wage Variable and solving NA issues with some other variables
H1B <- H1B %>% 
  mutate(PW_WAGE_HOURLY = case_when(WAGE_OFFER_UNIT_OF_PAY == "Year" ~ PW_WAGE/2080,
                                    WAGE_OFFER_UNIT_OF_PAY == "Month" ~ PW_WAGE/160,
                                    WAGE_OFFER_UNIT_OF_PAY == "Bi-Weekly" ~ PW_WAGE/80,
                                    WAGE_OFFER_UNIT_OF_PAY == "Week" ~ PW_WAGE/40)) %>% 
  filter(PW_WAGE_HOURLY > 5) %>% 
  dplyr::select(-c(PW_WAGE)) %>% 
  mutate(CLASS_OF_ADMISSION = if_else(is.na(CLASS_OF_ADMISSION),"UNK",CLASS_OF_ADMISSION),
         PW_SKILL_LEVEL = if_else(is.na(PW_SKILL_LEVEL),0,PW_SKILL_LEVEL),
         FOREIGN_WORKER_ED_INST_US = as.character(FOREIGN_WORKER_ED_INST_US),
         FOREIGN_WORKER_ED_INST_US = if_else(is.na(FOREIGN_WORKER_ED_INST_US), "UNK", FOREIGN_WORKER_ED_INST_US),
         FOREIGN_WORKER_EXP_WITH_EMPL = as.character(FOREIGN_WORKER_EXP_WITH_EMPL),
         FOREIGN_WORKER_EXP_WITH_EMPL = if_else(is.na(FOREIGN_WORKER_EXP_WITH_EMPL), "UNK", FOREIGN_WORKER_EXP_WITH_EMPL))

#Dropping remaining NA's and converting Waiting Period to Numeric
H1B <- H1B %>% 
  drop_na() %>% 
  mutate(WAITING_PERIOD = as.numeric(WAITING_PERIOD))

```

```{r}
H1B <- H1B %>%
  group_by(COUNTRY_OF_CITIZENSHIP) %>%
  filter(n() >= 20) %>% 
  ungroup()
```

```{r}
set.seed(1234)
H1B.1 <- H1B %>%
  filter(CASE_STATUS == 1) %>% 
  slice_sample(n = 2506) 

H1B.2 <- H1B %>% 
  filter(CASE_STATUS == 0)

H1B <- H1B.1 %>% 
  rbind(H1B.2)

```


```{r}
#Creating Dummy Variables
H1B_dummies <- dummy_cols(.data = H1B, select_columns = c("PW_SKILL_LEVEL", "WAGE_OFFER_UNIT_OF_PAY", "MINIMUM_EDUCATION", "COUNTRY_OF_CITIZENSHIP", "CLASS_OF_ADMISSION", "FOREIGN_WORKER_EDUCATION", "FOREIGN_WORKER_ED_INST_US", "FOREIGN_WORKER_REQ_EXPERIENCE", "FOREIGN_WORKER_EXP_WITH_EMPL"))

#Deselecting Variables that dummies were created for
H1B_dummies <- H1B_dummies %>%
  select(-c("PW_SKILL_LEVEL", "WAGE_OFFER_UNIT_OF_PAY", "MINIMUM_EDUCATION", "COUNTRY_OF_CITIZENSHIP", "CLASS_OF_ADMISSION", "FOREIGN_WORKER_EDUCATION", "FOREIGN_WORKER_ED_INST_US", "FOREIGN_WORKER_REQ_EXPERIENCE", "FOREIGN_WORKER_EXP_WITH_EMPL"))

#Creating Factors
H1B <- H1B %>% 
  mutate(PW_SKILL_LEVEL = as.factor(PW_SKILL_LEVEL),
         WAGE_OFFER_UNIT_OF_PAY = as.factor(WAGE_OFFER_UNIT_OF_PAY),
         MINIMUM_EDUCATION = as.factor(MINIMUM_EDUCATION),
         COUNTRY_OF_CITIZENSHIP = as.factor(COUNTRY_OF_CITIZENSHIP),
         CLASS_OF_ADMISSION = as.factor(CLASS_OF_ADMISSION),
         FOREIGN_WORKER_EDUCATION = as.factor(FOREIGN_WORKER_EDUCATION),
         FOREIGN_WORKER_ED_INST_US = as.factor(FOREIGN_WORKER_ED_INST_US),
         FOREIGN_WORKER_REQ_EXPERIENCE = as.factor(FOREIGN_WORKER_REQ_EXPERIENCE),
         FOREIGN_WORKER_EXP_WITH_EMPL = as.factor(FOREIGN_WORKER_EXP_WITH_EMPL)) 


#glimpse(H1B)

```

### Training and Testing Data Splits

```{r}
set.seed(1234)

data_split <- initial_split(H1B, prop = 0.7)

H1B_Train <- training(data_split)
H1B_Test <- testing(data_split)

write.csv(H1B_Train, file = "../Data/H1B_Train.csv")
write.csv(H1B_Test, file = "../Data/H1B_Test.csv")
```

```{r}
set.seed(1234)
data_split <- initial_split(H1B_dummies, prop = 0.7)

H1B_Train_dummies <- training(data_split)
H1B_Test_dummies <- testing(data_split)

write.csv(H1B_Train_dummies, file = "../Data/H1B_Train_Dummies.csv")
write.csv(H1B_Test_dummies, file = "../Data/H1B_Test_Dummies.csv")
```

```{r}
H1B3 <- H1B %>% #filtering for countries that appeared less than 100 times
  group_by(COUNTRY_OF_CITIZENSHIP) %>%
  filter(n() >= 100) %>%
  ungroup() 

H1B3 <- H1B3 %>% #filtering for class of admission that appear less than 100 times
  group_by(CLASS_OF_ADMISSION) %>%
  filter(n() >= 100) %>%
  ungroup()

H1B3 <- H1B3 %>% #transforming Wage Offer Unit of Pay to Yearly or other
  mutate(WAGE_OFFER_UNIT_OF_PAY = case_when(WAGE_OFFER_UNIT_OF_PAY == "Year" ~ 1,
                                            T ~ 0))
  
set.seed(1234) #creating new split data set for logit ran with cv.glm(K=10)
H1B.4 <- H1B3 %>%
  filter(CASE_STATUS == 1) %>% 
  slice_sample(n = 2261) #2261 is the to match the amount of declines

H1B.5 <- H1B3 %>% 
  filter(CASE_STATUS == 0)

H1B.6 <- H1B.4 %>% #combining data set
  rbind(H1B.5)

#writing logit data set to local
write.csv(H1B.6, file = "../Data/H1B_logit.csv")
```

