---
title: "ML_Project"
author: "Concillia Mpofu"
date: "2022-12-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR2)
library(leaps)
library(tidyverse)
```

```{r}
H1B_Train <-read_csv('./Data/H1B_Train.csv')

H1B_Train
```

```{r}
H1B_Train <- H1B_Train %>% 
  drop_na() %>% 
  mutate(CASE_STATUS = as.numeric(CASE_STATUS),
         REFILE = as.factor(REFILE),
         FW_OWNERSHIP_INTEREST = as.factor(FW_OWNERSHIP_INTEREST),
         PW_SKILL_LEVEL = as.factor(PW_SKILL_LEVEL),
         WAGE_OFFER_UNIT_OF_PAY = as.factor(WAGE_OFFER_UNIT_OF_PAY),
         MINIMUM_EDUCATION = as.factor(MINIMUM_EDUCATION),
         REQUIRED_TRAINING = as.factor(REQUIRED_TRAINING),
         REQUIRED_EXPERIENCE = as.factor(REQUIRED_EXPERIENCE),
         ACCEPT_ALT_OCCUPATION = as.factor(ACCEPT_ALT_OCCUPATION),
         FOREIGN_LANGUAGE_REQUIRED = as.factor(FOREIGN_LANGUAGE_REQUIRED),
         OFFERED_TO_APPL_FOREIGN_WORKER = as.factor(OFFERED_TO_APPL_FOREIGN_WORKER),
         FOREIGN_WORKER_LIVE_ON_PREM = as.factor(FOREIGN_WORKER_LIVE_ON_PREM),
         FOREIGN_WORKER_LIVE_IN_DOM_SER = as.factor(FOREIGN_WORKER_LIVE_IN_DOM_SER),
         PROFESSIONAL_OCCUPATION = as.factor(PROFESSIONAL_OCCUPATION),
         APP_FOR_COLLEGE_U_TEACHER = as.factor(APP_FOR_COLLEGE_U_TEACHER),
         COUNTRY_OF_CITIZENSHIP = as.factor(COUNTRY_OF_CITIZENSHIP),
         CLASS_OF_ADMISSION = as.factor(CLASS_OF_ADMISSION),
         FOREIGN_WORKER_EDUCATION = as.factor(FOREIGN_WORKER_EDUCATION),
         FOREIGN_WORKER_ED_INST_US = as.factor(FOREIGN_WORKER_ED_INST_US),
         FOREIGN_WORKER_REQ_EXPERIENCE = as.factor(FOREIGN_WORKER_REQ_EXPERIENCE),
         FOREIGN_WORKER_EXP_WITH_EMPL = as.factor(FOREIGN_WORKER_EXP_WITH_EMPL),
         FOREIGN_WORKER_EMPL_PAY_FOR_ED = as.factor(FOREIGN_WORKER_EMPL_PAY_FOR_ED),
         FOREIGN_WORKER_CURR_EMPLOYED = as.factor(FOREIGN_WORKER_CURR_EMPLOYED),
         EMPLOYER_COMPLETED_APPLICATION = as.factor(EMPLOYER_COMPLETED_APPLICATION)) 

glimpse(H1B_Train)

```


```{r}
reg.fit <- regsubsets(CASE_STATUS ~ ., data = H1B_Train)
sum_reg <- summary(reg.fit)
```

