---
title: "pca/pls"
author: "Yuka Chen"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)
library(lubridate)
library(tidymodels)
library(GGally)
library(pls)
library(cowplot)
library("gridExtra")                        # Load gridExtra package
library(MASS)
library(boot)
library(leaps)
library(glmnet)
```

```{r}
H1B_Train <- read_csv("../Data/H1B_Train.csv")
H1B_Test <- read_csv("../Data/H1B_Test.csv")
H1B <- read_csv("../Data/H1B.csv")

```

```{r}
H1B_Train |> 
  select(-`...1`) -> H1B_Train

H1B_Test |> 
  select(-`...1`) -> H1B_Test
```

Train as factor:

```{r}

H1B_Train_factor <- H1B_Train %>% 
  mutate(CASE_STATUS = as.numeric(CASE_STATUS),
         REFILE = as.factor(REFILE),
         FW_OWNERSHIP_INTEREST = as.factor(FW_OWNERSHIP_INTEREST),
         PW_SKILL_LEVEL = as.factor(PW_SKILL_LEVEL),
         WAGE_OFFER_UNIT_OF_PAY = as.factor(WAGE_OFFER_UNIT_OF_PAY),
         MINIMUM_EDUCATION = as.factor(MINIMUM_EDUCATION),
         REQUIRED_TRAINING = as.factor(REQUIRED_TRAINING),
         REQUIRED_EXPERIENCE = as.factor(REQUIRED_EXPERIENCE),
         ACCEPT_ALT_OCCUPATION = as.factor(ACCEPT_ALT_OCCUPATION),
         FOREIGN_LANGUAGE_REQUIRED = as.factor(FOREIGN_LANGUAGE_REQUIRED),
         FOREIGN_WORKER_LIVE_ON_PREM = as.factor(FOREIGN_WORKER_LIVE_ON_PREM),
         FOREIGN_WORKER_LIVE_IN_DOM_SER = as.factor(FOREIGN_WORKER_LIVE_IN_DOM_SER),
         PROFESSIONAL_OCCUPATION = as.factor(PROFESSIONAL_OCCUPATION),
         APP_FOR_COLLEGE_U_TEACHER = as.factor(APP_FOR_COLLEGE_U_TEACHER),
         COUNTRY_OF_CITIZENSHIP = as.factor(COUNTRY_OF_CITIZENSHIP),
         CLASS_OF_ADMISSION = as.factor(CLASS_OF_ADMISSION),
         FOREIGN_WORKER_EDUCATION = as.factor(FOREIGN_WORKER_EDUCATION),
         FOREIGN_WORKER_ED_INST_US = as.factor(FOREIGN_WORKER_ED_INST_US),
         FOREIGN_WORKER_REQ_EXPERIENCE = as.factor(FOREIGN_WORKER_REQ_EXPERIENCE),
         FOREIGN_WORKER_EXP_WITH_EMPL = as.factor(FOREIGN_WORKER_EXP_WITH_EMPL),
         FOREIGN_WORKER_EMPL_PAY_FOR_ED = as.factor(FOREIGN_WORKER_EMPL_PAY_FOR_ED),
         FOREIGN_WORKER_CURR_EMPLOYED = as.factor(FOREIGN_WORKER_CURR_EMPLOYED),
         EMPLOYER_COMPLETED_APPLICATION = as.factor(EMPLOYER_COMPLETED_APPLICATION))
```

Test as factor:

```{r}
H1B_Test_factor <- H1B_Test %>% 
  mutate(CASE_STATUS = as.factor(CASE_STATUS),
         REFILE = as.factor(REFILE),
         FW_OWNERSHIP_INTEREST = as.factor(FW_OWNERSHIP_INTEREST),
         PW_SKILL_LEVEL = as.factor(PW_SKILL_LEVEL),
         WAGE_OFFER_UNIT_OF_PAY = as.factor(WAGE_OFFER_UNIT_OF_PAY),
         MINIMUM_EDUCATION = as.factor(MINIMUM_EDUCATION),
         REQUIRED_TRAINING = as.factor(REQUIRED_TRAINING),
         REQUIRED_EXPERIENCE = as.factor(REQUIRED_EXPERIENCE),
         ACCEPT_ALT_OCCUPATION = as.factor(ACCEPT_ALT_OCCUPATION),
         FOREIGN_LANGUAGE_REQUIRED = as.factor(FOREIGN_LANGUAGE_REQUIRED),
         OFFERED_TO_APPL_FOREIGN_WORKER = as.factor(OFFERED_TO_APPL_FOREIGN_WORKER),
         FOREIGN_WORKER_LIVE_ON_PREM = as.factor(FOREIGN_WORKER_LIVE_ON_PREM),
         FOREIGN_WORKER_LIVE_IN_DOM_SER = as.factor(FOREIGN_WORKER_LIVE_IN_DOM_SER),
         PROFESSIONAL_OCCUPATION = as.factor(PROFESSIONAL_OCCUPATION),
         APP_FOR_COLLEGE_U_TEACHER = as.factor(APP_FOR_COLLEGE_U_TEACHER),
         COUNTRY_OF_CITIZENSHIP = as.factor(COUNTRY_OF_CITIZENSHIP),
         CLASS_OF_ADMISSION = as.factor(CLASS_OF_ADMISSION),
         FOREIGN_WORKER_EDUCATION = as.factor(FOREIGN_WORKER_EDUCATION),
         FOREIGN_WORKER_ED_INST_US = as.factor(FOREIGN_WORKER_ED_INST_US),
         FOREIGN_WORKER_REQ_EXPERIENCE = as.factor(FOREIGN_WORKER_REQ_EXPERIENCE),
         FOREIGN_WORKER_EXP_WITH_EMPL = as.factor(FOREIGN_WORKER_EXP_WITH_EMPL),
         FOREIGN_WORKER_EMPL_PAY_FOR_ED = as.factor(FOREIGN_WORKER_EMPL_PAY_FOR_ED),
         FOREIGN_WORKER_CURR_EMPLOYED = as.factor(FOREIGN_WORKER_CURR_EMPLOYED),
         EMPLOYER_COMPLETED_APPLICATION = as.factor(EMPLOYER_COMPLETED_APPLICATION))
```




Correlation:
```{r}
COE_HIB <- round(cor(H1B_Train),
      digits = 2)
head(COE_HIB, 5)
```

```{r}
map_dbl(H1B_Train, ~ sum(is.na(.)))
# no NA
```

```{r}
cor(H1B_Train, use = "complete.obs")
```

```{r}
(abs(cor(H1B_Train, use = "complete.obs"))-.1) |> round(0)
```

```{r}
reg <-  glm(CASE_STATUS ~ ., data = H1B_Train)
X <-  model.matrix(reg)
```

```{r}
pc <- stats::prcomp(X)
pc
```

```{r}
100*(pc$sdev/sum(pc$sdev)) |> round(3)
```

```{r}
summary(pc)
```

```{r}
screeplot(pc)
```

```{r}
pc$rotation[,1] |> round(3)
```

```{r}
pc_s <- prcomp(X[,-1], scale = TRUE)
pc_s
```

```{r}
summary(pc_s)
```

```{r}
screeplot(pc_s)
```

```{r}
summary(lm(CASE_STATUS ~ ., data = H1B_Train))
```

# PCR

### PCR WITH CV - HW
```{r}
# Create cross validation solution and check for lowest MSE
set.seed(1234)
pcr_fit <- pcr(CASE_STATUS ~ ., data = H1B_Train, scale = TRUE, validation = "CV")
summary(pcr_fit)
```

### PCR M
```{r}
pcr_fitM <- pcr(CASE_STATUS ~ ., data = H1B_Train, scale = TRUE, ncomp = 25)
yHat_pcr <- predict(pcr_fitM, newdata = H1B_Test)
mean((yHat_pcr - H1B_Test$CASE_STATUS)^2)
```

```{r}
R2_pcr  <- as.numeric(R2(pcr_reg, estimate="CV")$val)
MSEP_pcr <- as.numeric(MSEP(pcr_reg, estimate="CV")$val)
 
which_max_R2 <- which.max(R2_pcr)- 1
which_max_MSEP<- which.min(MSEP_pcr)- 1
max_R2_pcr <- max(R2_pcr)
min_MSEP_pcr <- min(MSEP_pcr)

tibble(which_max_R2, which_max_MSEP,max_R2_pcr,min_MSEP_pcr)
```

For PC regression the best model has all 24 PCs The best model has the highest R2 at 0.1488997 and the lowest MSEP at 0.02256555.

# PLS

### PLSR WITH CV
```{r}
set.seed(1234)
pls_fit <- plsr(CASE_STATUS ~ ., data = H1B_Train, scale = TRUE, validation = "CV")
summary(pls_fit)
```

```{r}
pls_fitM <- plsr(CASE_STATUS ~ ., data = H1B_Train, scale = TRUE, ncomp = 17)
yHat_pls <- predict(pls_fitM, newdata = H1B_Test)
mean((yHat_pls - H1B_Test$CASE_STATUS)^2)
```

```{r}
R2_pls  <- as.numeric(R2(pls_reg, estimate="CV")$val)
MSEP_pls <- as.numeric(MSEP(pls_reg, estimate="CV")$val)
 
which_max_R2_pls <- which.max(R2_pls) -1
which_min_RSEP_pls <- which.min(MSEP_pls) -1
max_R2_pls <- max(R2_pls)
min_MSEP_pls <- min(MSEP_pls)
tibble(which_max_R2_pls, which_min_RSEP_pls,max_R2_pls,min_MSEP_pls)

```

For PLS regression the best model has 8 PCs but barely. The best model has the highest cross-validation R2 at 0.02256751 and the lowest MSEP at 0.02256272.

```{r}
Predicted.rr <- ifelse(yHat_pls >= 1.5, 2, 1)[,1]
table(H1B_Test$CASE_STATUS, Predicted.rr)
```

#### plot
```{r}
layout(matrix(c(2,1), nrow = 2, ncol = 1, byrow = TRUE))
validationplot(pcr_fit)
mtext("PCR",side = 4)
validationplot(pls_fit)
mtext("PLS",side = 4)
mtext("Validation", side=6, outer=TRUE, cex=2)
```


```{r}
layout(matrix(c(2,1), nrow = 2, ncol = 2, byrow = TRUE))
windows(width=9, height=6)
par(mfrow=c(1,2), oma=c(0,0,2,0))
plot(pcr_fit, "validation", val.type = "MSEP", legendpos = "right", main = "PCR")
plot(pls_fit, "validation", val.type = "MSEP", legendpos = "right", main = "PLS")
title("My 'Title' in a strange place", line = -21, outer = TRUE)

```

